### PR TITLE
Create ETHproductions-1.japt

### PR DESCRIPTION
**Pull request by ETHproductions**
My first submission; hopefully it's legal. Use [this permalink](http://ethproductions.github.io/japt/?v=master&code=YHDOQyLDAHQoJ1NUT1AhJyki&input=) to test the first iteration.

### CODE REVIEW

**Comment by ETHproductions** [comment]
Can I add PHP as a fourth iteration? No modification needed to the code ;)

**Comment by schas002** [comment]
Nope. :P

**Comment by schas002** [comment]
I'm on mobile right now, will review in a few hours.

**Comment by ETHproductions** [comment]
You may want to add a rule that "quine" iterations (the code just prints out itself) are disallowed.

**Comment by schas002** [comment]
Okay. :3

**Comment by schas002** [comment]
`Error: Japt.stdout must be sent to an HTMLElement` :cry: I have to add this as an issue to the Japt repo.

**Comment by schas002** [comment]
Added loophole about "quine" iterations.

**Comment by ETHproductions** [comment]
Awesome, thanks. Refreshing the page usually gets rid of that error message.

**Comment by ETHproductions** [comment]
Can you try running the program again? This problem should be fixed.

**Comment by schas002** [comment]
I'm currently on mobile. So I'm unable to. Don't worry, I'll eventually test it.

**Comment by schas002** [comment]
First iteration _finally_ works. Pls wait, while I merge...

**Comment by schas002** [comment]
> This branch has no conflicts with the base branch

Status green.

**Pull request merged**
