### PR TITLE
Create Conor-OBrien-2.jolf

### PR DESCRIPTION
**Pull request by ConorOBrien-Foxx**
my newest submission

### CODE REVIEW

**Comment by schas002** [comment]
I'm on mobile right now, I'll review later.

**Comment by schas002** [comment]
Something prevents me to check the first iteration. Jolf doesn't work on my browser (Firefox 45.0.2), even partially.

**Comment by ConorOBrien-Foxx** [comment]
Yeah, jolf is borked atm and I don't know why.

**Comment by ConorOBrien-Foxx** [comment]
hey try again, jolf works now

**Comment by schas002** [comment]
It doesn't work. When I press "Run", it is stuck forever in the pressed state, and the browser had to be reset on Firefox, and I had to close the tab myself in mobile Chrome.

**Comment by ConorOBrien-Foxx** [comment]
Huh. That's weird.

**Pull request closed without merging**
